### ISSUE TITLE
Import #12 module="debug" error: module is not an object or function

### ISSUE THREAD

**Issue by 0xbe1** [as-pect/as-pect#387]
Hi,

I want to test this simple function

```ts
export function add(a: i32, b: i32): i32 {
  return a + b;
}
```

so I add a simple test to example.spec.ts

```ts
import { add } from "../../build/debug"

describe("example", () => {
  it("should be 42 (@)", () => {
    expect(add(1, 2)).toBe(3, "1 + 2 is 3");
  }) 
})
```

I import from "debug" because I have this line of code in package.json, and I run `yarn asbuild` before `yarn test`:

```json
  "scripts": {
    "asbuild:debug": "asc assembly/index.ts --target debug",
    "asbuild:release": "asc assembly/index.ts --target release",
    "asbuild": "yarn asbuild:debug && yarn asbuild:release",
    "test": "asp --verbose",
    "start": "npx serve ."
  }
```

however I got this error when I try to run `yarn test`:

```
Assemblyscript Folder:assemblyscript
[Log] Compiler loaded in 344.249ms.
[Log] Using configuration /Users/0xbe1/source/0xbe1/web3/graph-ts-playground/as-pect.config.js
[Log] Using VerboseReporter
[Log] Including files: assembly/__tests__/**/*.spec.ts
[Log] Running tests that match: (:?)
[Log] Running groups that match: (:?)
[Log] Effective command line args:
  [TestFile.ts] node_modules/@as-pect/assembly/assembly/index.ts --runtime incremental --debug --binaryFile output.wasm --explicitStart --use ASC_RTRACE=1 --exportTable --importMemory --transform /Users/0xbe1/source/0xbe1/web3/graph-ts-playground/node_modules/@as-pect/core/lib/transform/index.js

/Users/0xbe1/source/0xbe1/web3/graph-ts-playground/node_modules/assemblyscript/lib/loader/umd/index.js:423
    const instance = new WebAssembly.Instance(module, imports);
                     ^

TypeError: WebAssembly.Instance(): Import #12 module="debug" error: module is not an object or function
    at instantiateSync (/Users/0xbe1/source/0xbe1/web3/graph-ts-playground/node_modules/assemblyscript/lib/loader/umd/index.js:423:22)
    at imports (/Users/0xbe1/source/0xbe1/web3/graph-ts-playground/as-pect.config.js:31:16)
    at runBinary (/Users/0xbe1/source/0xbe1/web3/graph-ts-playground/node_modules/@as-pect/cli/lib/run.js:455:26)
    at /Users/0xbe1/source/0xbe1/web3/graph-ts-playground/node_modules/@as-pect/cli/lib/run.js:673:42
    at wrappedCallback (/Users/0xbe1/source/0xbe1/web3/graph-ts-playground/node_modules/assemblyscript/cli/asc.js:481:14)
    at Object.main (/Users/0xbe1/source/0xbe1/web3/graph-ts-playground/node_modules/assemblyscript/cli/asc.js:1225:10)
    at /Users/0xbe1/source/0xbe1/web3/graph-ts-playground/node_modules/@as-pect/cli/lib/run.js:624:17
    at Array.forEach (<anonymous>)
    at run (/Users/0xbe1/source/0xbe1/web3/graph-ts-playground/node_modules/@as-pect/cli/lib/run.js:622:36)
    at Object.asp (/Users/0xbe1/source/0xbe1/web3/graph-ts-playground/node_modules/@as-pect/cli/lib/index.js:64:9)
    at Object.<anonymous> (/Users/0xbe1/source/0xbe1/web3/graph-ts-playground/node_modules/@as-pect/cli/lib/test.js:2:28)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
error Command failed with exit code 1.
```

a reproducible code repo can be found https://github.com/0xbe1/graph-ts-playground/tree/import-graph-ts

any help? thanks!

**Comment by 0xbe1** [comment]
> Looks like you are trying to import the wasm instead of the assemblyscript source. Try pointing to the
> 
> ```ts
> import { add } from "..";
> ```
> 
> as-pect will compile your tests along with the code.

This works! Thank you :)
